# For all possible configuration options see:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/export-server"
    schedule:
      interval: "daily"
    reviewers:
      - "striezel"
    ignore:
      # Phantom.js uses the same major version of uuid (3.x), and in order to
      # avoid having two different versions, uuid is not updated.
      - dependency-name: "uuid"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "striezel"
