node_14:
  image: node:14-alpine
  stage: build
  before_script:
    - node --version
    - npm --version
  script:
    - cd ./export-server
    - npm install

node_16:
  image: node:16-alpine
  stage: build
  before_script:
    - node --version
    - npm --version
  script:
    - cd ./export-server
    - npm install

node_18:
  image: node:18-alpine
  stage: build
  before_script:
    - node --version
    - npm --version
  script:
    - cd ./export-server
    - npm install
